version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - setup_remote_docker
      
  node-server:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run: 
          command: npm test
          working_directory: ./server
  
  react-client:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./client       
      - run:
          command: npm test
          working_directory: ./client
  
  docker-publish:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            echo "$DOCKER_PASS" | docker login -u "jszandula" --password-stdin
            sudo docker build ./server -t jszandula/server
            sudo docker push jszandula/server
      - run:
          command: |
            echo "$DOCKER_PASS" | docker login -u "jszandula" --password-stdin
            sudo docker build ./client -t jszandula/client
            sudo docker push jszandula/client
workflows:
    build-and-test:
      jobs:
        - build:
            filters:
              branches:
                only:
                  - master
        - node-server:
            requires:
              - build
        - react-client:
            requires:
              - build
        - docker-publish:
            requires:
              - react-client
              - node-server