version: 2.1
orbs:
    node: circleci/node@2.1.0
jobs:
    build-and-test:
        executor:
            name: node/default
        steps:
            - checkout
            - node/install-packages:
                appr-dir: ./server
            - run: npm install
            - run: 
                command: npm test
                working_directory: ./server
workflows:
    build-and-test:
        jobs:
            - build-and-test